project:
  type: website
  output-dir: docs
  resources: 
    - "cv/*"

website:
  title: "Stepan Polikanov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
