project:
  type: website
  output-dir: docs
  resources: 
    - cv/
    - styling/

website:
  title: "Stepan Polikanov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/sapolikanov/
      - icon: github
        href: https://github.com/sapolikanov
      - icon: twitter-x
        href: https://x.com/spolikanov
      - text: "{{< iconify fa6-brands:orcid >}}"
        href: https://orcid.org/0000-0002-2329-2750
format:
  html:
    theme: cosmo
    css: styling/styles.css
    toc: true
